### ISSUE TITLE
Bug: jupyter nbextension install attempts to create directories outside virtualenv

### ISSUE THREAD

**Issue by madanh** [vega/ipyvega#65]
The following installation step

`jupyter nbextension install --py vega`

fails when run inside virtualenv while attempting to modify global distribution directories

```
(mcmc)madanh@madanh ~/.virtualenvs/mcmc $ jupyter nbextension install --py vega
Installing /home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/vega/static -> jupyter-vega
Traceback (most recent call last):
  File "/home/madanh/.virtualenvs/mcmc/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/notebook/nbextensions.py", line 900, in start
    super(NBExtensionApp, self).start()
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/notebook/nbextensions.py", line 678, in start
    self.install_extensions()
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/notebook/nbextensions.py", line 657, in install_extensions
    **kwargs
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/madanh/.virtualenvs/mcmc/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

**Comment by madanh** [comment]
from altair [docs](https://altair-viz.github.io/installation.html#installation) a fix is to add `--sys-prefix` flag. Consider adjusting the readme

**Comment by jakevdp** [comment]
Done – thanks!
